name: CI/client

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

defaults:
  run:
    shell: bash
    working-directory: client

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14

      - uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-build-client-v2-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/package-lock.lock') }}
          path: |
            ./client/node_modules
          restore-keys: |
            ${{ runner.os }}-build-client-v2-${{ hashFiles('**/yarn.lock') }}-
            ${{ runner.os }}-build-client-v2

      - name: Install dependencies
        run: yarn

  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    environment:
      name: staging_pr
      url: https://pr-${{ github.event.number }}--myprofilepro.netlify.app
    needs:
      - build
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-build-client-v2-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/package-lock.lock') }}
          path: |
            ./client/node_modules

      - name: Set variables in nuxt.config.json
        run: |
          pwd
          ls
          sed -i -E "s|##API_BASE_URL##|${API_BASE_URL}|" nuxt.config.js
        env:
          API_BASE_URL: https://my-profile-pr-${{ github.event.number }}.herokuapp.com

      - name: Generate
        run: yarn generate --fail-on-error

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './client/dist'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-commit-comment: true
          overwrites-pull-request-comment: true
          alias: pr-${{ github.event.number }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1