name: Quality Api

on:
  workflow_run:
    workflows: ["Build Api]
    types:
      - completed
      - requested

defaults:
  run:
    shell: bash
    working-directory: api

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: build
    container:
      image: eerison/myprofile:dev
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - uses: actions/cache@v2
        with:
          key: build-${{ hashFiles('**/symfony.lock') }}-${{ env.GITHUB_REF_SLUG }}-${{ hashFiles('**/composer.lock') }}
          path: |
            ./api/bin/.phpunit
            ./api/vendor
            ./api/public
            ./api/config/jwt

      - name: See files
        run: |
          pwd
          ls -lha

      - name: Code Sniffer
        run: composer lint_phpcs

      - name: Symfony Containers
        run: composer lint_container

  test:
    name: Tests
    runs-on: ubuntu-latest
    needs: build
    env:
      APP_ENV: test
      MAILER_DSN: null://null
      XDEBUG_MODE: coverage
    container:
      image: eerison/myprofile:dev
    services:
      db:
        image: postgres
        env:
          POSTGRES_USER: myprofile
          POSTGRES_PASSWORD: 123456
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - uses: actions/cache@v2
        with:
          key: build-${{ hashFiles('**/symfony.lock') }}-${{ env.GITHUB_REF_SLUG }}-${{ hashFiles('**/composer.lock') }}
          path: |
            ./api/bin/.phpunit
            ./api/vendor
            ./api/public
            ./api/config/jwt

      - name: Setup Database
        run: composer db

      - name: Fixtures
        run: composer fixtures

      - name: See files
        run: |
          pwd
          ls -lha

      - name: Run Tests
        run: composer test

      - name: Codecov
        uses: codecov/codecov-action@v1