name: Receive a Pull request

on:
  workflow_run:
    workflows: [ "CI/api", "CI/client" ]
    types:
      - requested
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Notify Slack and send eMail
        run: ls -lha
